// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type Announcement struct {
	ID             uuid.UUID             `json:"id"`
	SpaceID        uuid.UUID             `json:"space_id"`
	Title          string                `json:"title"`
	Content        string                `json:"content"`
	Type           string                `json:"type"`
	TargetAudience []string              `json:"target_audience"`
	Priority       sql.NullString        `json:"priority"`
	Status         sql.NullString        `json:"status"`
	AuthorID       uuid.NullUUID         `json:"author_id"`
	ScheduledFor   sql.NullTime          `json:"scheduled_for"`
	ExpiresAt      sql.NullTime          `json:"expires_at"`
	Attachments    pqtype.NullRawMessage `json:"attachments"`
	IsPinned       sql.NullBool          `json:"is_pinned"`
	CreatedAt      sql.NullTime          `json:"created_at"`
	UpdatedAt      sql.NullTime          `json:"updated_at"`
}

// Audit trail for admin actions
type AuditLog struct {
	ID           uuid.UUID             `json:"id"`
	AdminUserID  uuid.UUID             `json:"admin_user_id"`
	Action       string                `json:"action"`
	ResourceType string                `json:"resource_type"`
	ResourceID   uuid.NullUUID         `json:"resource_id"`
	Details      pqtype.NullRawMessage `json:"details"`
	IpAddress    pqtype.Inet           `json:"ip_address"`
	UserAgent    sql.NullString        `json:"user_agent"`
	CreatedAt    time.Time             `json:"created_at"`
}

type Comment struct {
	ID              uuid.UUID      `json:"id"`
	PostID          uuid.UUID      `json:"post_id"`
	AuthorID        uuid.UUID      `json:"author_id"`
	ParentCommentID uuid.NullUUID  `json:"parent_comment_id"`
	Content         string         `json:"content"`
	LikesCount      sql.NullInt32  `json:"likes_count"`
	Status          sql.NullString `json:"status"`
	CreatedAt       sql.NullTime   `json:"created_at"`
	UpdatedAt       sql.NullTime   `json:"updated_at"`
}

type Community struct {
	ID          uuid.UUID             `json:"id"`
	SpaceID     uuid.UUID             `json:"space_id"`
	Name        string                `json:"name"`
	Description sql.NullString        `json:"description"`
	Category    string                `json:"category"`
	CoverImage  sql.NullString        `json:"cover_image"`
	MemberCount sql.NullInt32         `json:"member_count"`
	Status      sql.NullString        `json:"status"`
	PostCount   sql.NullInt32         `json:"post_count"`
	IsPublic    sql.NullBool          `json:"is_public"`
	CreatedBy   uuid.NullUUID         `json:"created_by"`
	Settings    pqtype.NullRawMessage `json:"settings"`
	CreatedAt   sql.NullTime          `json:"created_at"`
	UpdatedAt   sql.NullTime          `json:"updated_at"`
}

type CommunityMember struct {
	ID          uuid.UUID    `json:"id"`
	CommunityID uuid.UUID    `json:"community_id"`
	UserID      uuid.UUID    `json:"user_id"`
	Role        string       `json:"role"`
	Permissions []string     `json:"permissions"`
	JoinedAt    sql.NullTime `json:"joined_at"`
}

type Conversation struct {
	ID               uuid.UUID             `json:"id"`
	SpaceID          uuid.UUID             `json:"space_id"`
	Name             sql.NullString        `json:"name"`
	Avatar           sql.NullString        `json:"avatar"`
	Description      sql.NullString        `json:"description"`
	ConversationType sql.NullString        `json:"conversation_type"`
	LastMessageID    uuid.NullUUID         `json:"last_message_id"`
	LastMessageAt    sql.NullTime          `json:"last_message_at"`
	IsActive         sql.NullBool          `json:"is_active"`
	Settings         pqtype.NullRawMessage `json:"settings"`
	CreatedAt        sql.NullTime          `json:"created_at"`
	UpdatedAt        sql.NullTime          `json:"updated_at"`
}

type ConversationParticipant struct {
	ID                   uuid.UUID             `json:"id"`
	ConversationID       uuid.UUID             `json:"conversation_id"`
	UserID               uuid.UUID             `json:"user_id"`
	Role                 sql.NullString        `json:"role"`
	JoinedAt             sql.NullTime          `json:"joined_at"`
	LeftAt               sql.NullTime          `json:"left_at"`
	IsActive             sql.NullBool          `json:"is_active"`
	NotificationsEnabled sql.NullBool          `json:"notifications_enabled"`
	CustomSettings       pqtype.NullRawMessage `json:"custom_settings"`
}

type EmailQueue struct {
	ID             uuid.UUID             `json:"id"`
	SpaceID        uuid.UUID             `json:"space_id"`
	RecipientEmail string                `json:"recipient_email"`
	Subject        string                `json:"subject"`
	TemplateName   sql.NullString        `json:"template_name"`
	TemplateData   pqtype.NullRawMessage `json:"template_data"`
	Status         sql.NullString        `json:"status"`
	SentAt         sql.NullTime          `json:"sent_at"`
	ErrorMessage   sql.NullString        `json:"error_message"`
	RetryCount     sql.NullInt32         `json:"retry_count"`
	CreatedAt      sql.NullTime          `json:"created_at"`
}

type Event struct {
	ID                   uuid.UUID      `json:"id"`
	SpaceID              uuid.UUID      `json:"space_id"`
	Title                string         `json:"title"`
	Description          sql.NullString `json:"description"`
	Category             string         `json:"category"`
	Location             sql.NullString `json:"location"`
	VenueDetails         sql.NullString `json:"venue_details"`
	StartDate            time.Time      `json:"start_date"`
	EndDate              time.Time      `json:"end_date"`
	Timezone             sql.NullString `json:"timezone"`
	Organizer            uuid.NullUUID  `json:"organizer"`
	Tags                 []string       `json:"tags"`
	ImageUrl             sql.NullString `json:"image_url"`
	MaxAttendees         sql.NullInt32  `json:"max_attendees"`
	CurrentAttendees     sql.NullInt32  `json:"current_attendees"`
	RegistrationRequired sql.NullBool   `json:"registration_required"`
	RegistrationDeadline sql.NullTime   `json:"registration_deadline"`
	Status               sql.NullString `json:"status"`
	IsPublic             sql.NullBool   `json:"is_public"`
	CreatedAt            sql.NullTime   `json:"created_at"`
	UpdatedAt            sql.NullTime   `json:"updated_at"`
}

type EventAttendee struct {
	ID           uuid.UUID      `json:"id"`
	EventID      uuid.UUID      `json:"event_id"`
	UserID       uuid.UUID      `json:"user_id"`
	Status       sql.NullString `json:"status"`
	Role         sql.NullString `json:"role"`
	RegisteredAt sql.NullTime   `json:"registered_at"`
	AttendedAt   sql.NullTime   `json:"attended_at"`
	Notes        sql.NullString `json:"notes"`
}

type File struct {
	ID           uuid.UUID             `json:"id"`
	SpaceID      uuid.UUID             `json:"space_id"`
	UserID       uuid.UUID             `json:"user_id"`
	Filename     string                `json:"filename"`
	OriginalName sql.NullString        `json:"original_name"`
	MimeType     sql.NullString        `json:"mime_type"`
	Size         sql.NullInt64         `json:"size"`
	Path         string                `json:"path"`
	Bucket       sql.NullString        `json:"bucket"`
	IsPublic     sql.NullBool          `json:"is_public"`
	Metadata     pqtype.NullRawMessage `json:"metadata"`
	UploadedAt   sql.NullTime          `json:"uploaded_at"`
}

type Follow struct {
	ID          uuid.UUID    `json:"id"`
	FollowerID  uuid.UUID    `json:"follower_id"`
	FollowingID uuid.UUID    `json:"following_id"`
	SpaceID     uuid.UUID    `json:"space_id"`
	CreatedAt   sql.NullTime `json:"created_at"`
}

type Group struct {
	ID               uuid.UUID             `json:"id"`
	SpaceID          uuid.UUID             `json:"space_id"`
	CommunityID      uuid.NullUUID         `json:"community_id"`
	Name             string                `json:"name"`
	Description      sql.NullString        `json:"description"`
	Category         string                `json:"category"`
	GroupType        string                `json:"group_type"`
	Avatar           sql.NullString        `json:"avatar"`
	Banner           sql.NullString        `json:"banner"`
	MemberCount      sql.NullInt32         `json:"member_count"`
	PostCount        sql.NullInt32         `json:"post_count"`
	Status           sql.NullString        `json:"status"`
	Visibility       sql.NullString        `json:"visibility"`
	AllowInvites     sql.NullBool          `json:"allow_invites"`
	AllowMemberPosts sql.NullBool          `json:"allow_member_posts"`
	CreatedBy        uuid.NullUUID         `json:"created_by"`
	Tags             []string              `json:"tags"`
	Settings         pqtype.NullRawMessage `json:"settings"`
	CreatedAt        sql.NullTime          `json:"created_at"`
	UpdatedAt        sql.NullTime          `json:"updated_at"`
}

type GroupApplication struct {
	ID          uuid.UUID      `json:"id"`
	RoleID      uuid.UUID      `json:"role_id"`
	UserID      uuid.UUID      `json:"user_id"`
	Message     sql.NullString `json:"message"`
	Status      sql.NullString `json:"status"`
	AppliedAt   sql.NullTime   `json:"applied_at"`
	ReviewedAt  sql.NullTime   `json:"reviewed_at"`
	ReviewedBy  uuid.NullUUID  `json:"reviewed_by"`
	ReviewNotes sql.NullString `json:"review_notes"`
}

type GroupMember struct {
	ID          uuid.UUID     `json:"id"`
	GroupID     uuid.UUID     `json:"group_id"`
	UserID      uuid.UUID     `json:"user_id"`
	Role        string        `json:"role"`
	JoinedAt    sql.NullTime  `json:"joined_at"`
	InvitedBy   uuid.NullUUID `json:"invited_by"`
	Permissions []string      `json:"permissions"`
}

type GroupRole struct {
	ID             uuid.UUID      `json:"id"`
	GroupID        uuid.UUID      `json:"group_id"`
	Name           string         `json:"name"`
	Description    sql.NullString `json:"description"`
	SlotsTotal     int32          `json:"slots_total"`
	SlotsFilled    sql.NullInt32  `json:"slots_filled"`
	Requirements   sql.NullString `json:"requirements"`
	SkillsRequired []string       `json:"skills_required"`
	CreatedAt      sql.NullTime   `json:"created_at"`
	UpdatedAt      sql.NullTime   `json:"updated_at"`
}

type Like struct {
	ID        uuid.UUID     `json:"id"`
	UserID    uuid.UUID     `json:"user_id"`
	PostID    uuid.NullUUID `json:"post_id"`
	CommentID uuid.NullUUID `json:"comment_id"`
	CreatedAt sql.NullTime  `json:"created_at"`
}

// Tracks all login attempts for security audit and brute-force protection
type LoginAttempt struct {
	ID            uuid.UUID      `json:"id"`
	Username      string         `json:"username"`
	IpAddress     pqtype.Inet    `json:"ip_address"`
	UserAgent     sql.NullString `json:"user_agent"`
	AttemptResult string         `json:"attempt_result"`
	AttemptedAt   time.Time      `json:"attempted_at"`
	UserID        uuid.NullUUID  `json:"user_id"`
	SpaceID       uuid.NullUUID  `json:"space_id"`
	SessionID     uuid.NullUUID  `json:"session_id"`
}

type MentorApplication struct {
	ID                   uuid.UUID       `json:"id"`
	ApplicantID          uuid.UUID       `json:"applicant_id"`
	SpaceID              uuid.UUID       `json:"space_id"`
	Industry             string          `json:"industry"`
	Company              sql.NullString  `json:"company"`
	Position             sql.NullString  `json:"position"`
	Experience           int32           `json:"experience"`
	Specialties          []string        `json:"specialties"`
	Achievements         sql.NullString  `json:"achievements"`
	MentorshipExperience sql.NullString  `json:"mentorship_experience"`
	Availability         json.RawMessage `json:"availability"`
	Motivation           sql.NullString  `json:"motivation"`
	ApproachDescription  sql.NullString  `json:"approach_description"`
	LinkedinProfile      sql.NullString  `json:"linkedin_profile"`
	Portfolio            sql.NullString  `json:"portfolio"`
	Status               sql.NullString  `json:"status"`
	SubmittedAt          sql.NullTime    `json:"submitted_at"`
	ReviewedAt           sql.NullTime    `json:"reviewed_at"`
	ReviewedBy           uuid.NullUUID   `json:"reviewed_by"`
	ReviewerNotes        sql.NullString  `json:"reviewer_notes"`
}

type MentorProfile struct {
	ID            uuid.UUID             `json:"id"`
	UserID        uuid.UUID             `json:"user_id"`
	SpaceID       uuid.UUID             `json:"space_id"`
	Industry      string                `json:"industry"`
	Company       sql.NullString        `json:"company"`
	Position      sql.NullString        `json:"position"`
	Experience    int32                 `json:"experience"`
	Specialties   []string              `json:"specialties"`
	Rating        sql.NullFloat64       `json:"rating"`
	ReviewCount   sql.NullInt32         `json:"review_count"`
	TotalSessions sql.NullInt32         `json:"total_sessions"`
	Availability  pqtype.NullRawMessage `json:"availability"`
	Description   sql.NullString        `json:"description"`
	Verified      sql.NullBool          `json:"verified"`
	IsAvailable   sql.NullBool          `json:"is_available"`
	CreatedAt     sql.NullTime          `json:"created_at"`
	UpdatedAt     sql.NullTime          `json:"updated_at"`
}

type MentoringSession struct {
	ID          uuid.UUID      `json:"id"`
	MentorID    uuid.UUID      `json:"mentor_id"`
	MenteeID    uuid.UUID      `json:"mentee_id"`
	SpaceID     uuid.UUID      `json:"space_id"`
	Topic       string         `json:"topic"`
	Status      sql.NullString `json:"status"`
	ScheduledAt time.Time      `json:"scheduled_at"`
	Duration    int32          `json:"duration"`
	MenteeNotes sql.NullString `json:"mentee_notes"`
	MentorNotes sql.NullString `json:"mentor_notes"`
	MeetingLink sql.NullString `json:"meeting_link"`
	Rating      sql.NullInt32  `json:"rating"`
	Review      sql.NullString `json:"review"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type Message struct {
	ID             uuid.UUID             `json:"id"`
	ConversationID uuid.UUID             `json:"conversation_id"`
	SenderID       uuid.UUID             `json:"sender_id"`
	RecipientID    uuid.NullUUID         `json:"recipient_id"`
	Content        sql.NullString        `json:"content"`
	Attachments    pqtype.NullRawMessage `json:"attachments"`
	MessageType    sql.NullString        `json:"message_type"`
	IsRead         sql.NullBool          `json:"is_read"`
	ReadAt         sql.NullTime          `json:"read_at"`
	Reactions      pqtype.NullRawMessage `json:"reactions"`
	ReplyToID      uuid.NullUUID         `json:"reply_to_id"`
	Status         sql.NullString        `json:"status"`
	CreatedAt      sql.NullTime          `json:"created_at"`
}

type Notification struct {
	ID             uuid.UUID             `json:"id"`
	ToUserID       uuid.UUID             `json:"to_user_id"`
	FromUserID     uuid.NullUUID         `json:"from_user_id"`
	Type           string                `json:"type"`
	Title          sql.NullString        `json:"title"`
	Message        sql.NullString        `json:"message"`
	RelatedID      uuid.NullUUID         `json:"related_id"`
	Metadata       pqtype.NullRawMessage `json:"metadata"`
	IsRead         sql.NullBool          `json:"is_read"`
	Priority       sql.NullString        `json:"priority"`
	ActionRequired sql.NullBool          `json:"action_required"`
	CreatedAt      sql.NullTime          `json:"created_at"`
}

type PastQuestion struct {
	ID            uuid.UUID      `json:"id"`
	SpaceID       uuid.UUID      `json:"space_id"`
	CourseCode    string         `json:"course_code"`
	CourseTitle   string         `json:"course_title"`
	Department    sql.NullString `json:"department"`
	AcademicYear  string         `json:"academic_year"`
	Semester      sql.NullString `json:"semester"`
	Instructor    sql.NullString `json:"instructor"`
	ExamType      sql.NullString `json:"exam_type"`
	FileUrl       string         `json:"file_url"`
	FileName      sql.NullString `json:"file_name"`
	FileSize      sql.NullInt32  `json:"file_size"`
	UploadedBy    uuid.UUID      `json:"uploaded_by"`
	Verified      sql.NullBool   `json:"verified"`
	VerifiedBy    uuid.NullUUID  `json:"verified_by"`
	VerifiedAt    sql.NullTime   `json:"verified_at"`
	DownloadCount sql.NullInt32  `json:"download_count"`
	CreatedAt     sql.NullTime   `json:"created_at"`
}

type Post struct {
	ID            uuid.UUID             `json:"id"`
	AuthorID      uuid.UUID             `json:"author_id"`
	SpaceID       uuid.UUID             `json:"space_id"`
	CommunityID   uuid.NullUUID         `json:"community_id"`
	GroupID       uuid.NullUUID         `json:"group_id"`
	ParentPostID  uuid.NullUUID         `json:"parent_post_id"`
	QuotedPostID  uuid.NullUUID         `json:"quoted_post_id"`
	Content       string                `json:"content"`
	Media         pqtype.NullRawMessage `json:"media"`
	Tags          []string              `json:"tags"`
	LikesCount    sql.NullInt32         `json:"likes_count"`
	CommentsCount sql.NullInt32         `json:"comments_count"`
	RepostsCount  sql.NullInt32         `json:"reposts_count"`
	QuotesCount   sql.NullInt32         `json:"quotes_count"`
	ViewsCount    sql.NullInt32         `json:"views_count"`
	IsPinned      sql.NullBool          `json:"is_pinned"`
	Visibility    sql.NullString        `json:"visibility"`
	Status        sql.NullString        `json:"status"`
	CreatedAt     sql.NullTime          `json:"created_at"`
	UpdatedAt     sql.NullTime          `json:"updated_at"`
}

type Report struct {
	ID              uuid.UUID             `json:"id"`
	SpaceID         uuid.UUID             `json:"space_id"`
	ReporterID      uuid.UUID             `json:"reporter_id"`
	ContentType     string                `json:"content_type"`
	ContentID       uuid.UUID             `json:"content_id"`
	Reason          string                `json:"reason"`
	Description     sql.NullString        `json:"description"`
	Status          sql.NullString        `json:"status"`
	Priority        sql.NullString        `json:"priority"`
	ReviewedBy      uuid.NullUUID         `json:"reviewed_by"`
	ReviewedAt      sql.NullTime          `json:"reviewed_at"`
	ModerationNotes sql.NullString        `json:"moderation_notes"`
	ActionsTaken    pqtype.NullRawMessage `json:"actions_taken"`
	CreatedAt       sql.NullTime          `json:"created_at"`
	UpdatedAt       sql.NullTime          `json:"updated_at"`
}

type Space struct {
	ID           uuid.UUID             `json:"id"`
	Name         string                `json:"name"`
	Slug         string                `json:"slug"`
	Description  sql.NullString        `json:"description"`
	Type         sql.NullString        `json:"type"`
	Logo         sql.NullString        `json:"logo"`
	CoverImage   sql.NullString        `json:"cover_image"`
	Location     sql.NullString        `json:"location"`
	Website      sql.NullString        `json:"website"`
	ContactEmail sql.NullString        `json:"contact_email"`
	PhoneNumber  sql.NullString        `json:"phone_number"`
	Status       sql.NullString        `json:"status"`
	Settings     pqtype.NullRawMessage `json:"settings"`
	CreatedAt    sql.NullTime          `json:"created_at"`
	UpdatedAt    sql.NullTime          `json:"updated_at"`
}

// Activity log for space-level events
type SpaceActivity struct {
	ID           uuid.UUID             `json:"id"`
	SpaceID      uuid.UUID             `json:"space_id"`
	ActivityType string                `json:"activity_type"`
	ActorID      uuid.NullUUID         `json:"actor_id"`
	ActorName    sql.NullString        `json:"actor_name"`
	Description  string                `json:"description"`
	Metadata     pqtype.NullRawMessage `json:"metadata"`
	CreatedAt    time.Time             `json:"created_at"`
}

// System-wide configuration settings
type SystemSetting struct {
	ID          uuid.UUID       `json:"id"`
	Key         string          `json:"key"`
	Value       json.RawMessage `json:"value"`
	Description sql.NullString  `json:"description"`
	UpdatedBy   uuid.NullUUID   `json:"updated_by"`
	CreatedAt   time.Time       `json:"created_at"`
	UpdatedAt   time.Time       `json:"updated_at"`
}

type TrendingTopic struct {
	ID         uuid.UUID       `json:"id"`
	SpaceID    uuid.UUID       `json:"space_id"`
	Name       string          `json:"name"`
	Category   sql.NullString  `json:"category"`
	PostCount  sql.NullInt32   `json:"post_count"`
	TrendScore sql.NullFloat64 `json:"trend_score"`
	Period     sql.NullString  `json:"period"`
	RecordedAt sql.NullTime    `json:"recorded_at"`
}

type TutorApplication struct {
	ID               uuid.UUID       `json:"id"`
	ApplicantID      uuid.UUID       `json:"applicant_id"`
	SpaceID          uuid.UUID       `json:"space_id"`
	Subjects         []string        `json:"subjects"`
	HourlyRate       sql.NullString  `json:"hourly_rate"`
	Availability     json.RawMessage `json:"availability"`
	Experience       sql.NullString  `json:"experience"`
	Qualifications   sql.NullString  `json:"qualifications"`
	TeachingStyle    sql.NullString  `json:"teaching_style"`
	Motivation       sql.NullString  `json:"motivation"`
	ReferenceLetters sql.NullString  `json:"reference_letters"`
	Status           sql.NullString  `json:"status"`
	SubmittedAt      sql.NullTime    `json:"submitted_at"`
	ReviewedAt       sql.NullTime    `json:"reviewed_at"`
	ReviewedBy       uuid.NullUUID   `json:"reviewed_by"`
	ReviewerNotes    sql.NullString  `json:"reviewer_notes"`
}

type TutorProfile struct {
	ID             uuid.UUID             `json:"id"`
	UserID         uuid.UUID             `json:"user_id"`
	SpaceID        uuid.UUID             `json:"space_id"`
	Subjects       []string              `json:"subjects"`
	HourlyRate     sql.NullString        `json:"hourly_rate"`
	Rating         sql.NullFloat64       `json:"rating"`
	ReviewCount    sql.NullInt32         `json:"review_count"`
	TotalSessions  sql.NullInt32         `json:"total_sessions"`
	Description    sql.NullString        `json:"description"`
	Availability   pqtype.NullRawMessage `json:"availability"`
	Experience     sql.NullString        `json:"experience"`
	Qualifications sql.NullString        `json:"qualifications"`
	Verified       sql.NullBool          `json:"verified"`
	IsAvailable    sql.NullBool          `json:"is_available"`
	CreatedAt      sql.NullTime          `json:"created_at"`
	UpdatedAt      sql.NullTime          `json:"updated_at"`
}

type TutoringSession struct {
	ID           uuid.UUID      `json:"id"`
	TutorID      uuid.UUID      `json:"tutor_id"`
	StudentID    uuid.UUID      `json:"student_id"`
	SpaceID      uuid.UUID      `json:"space_id"`
	Subject      string         `json:"subject"`
	Status       sql.NullString `json:"status"`
	ScheduledAt  time.Time      `json:"scheduled_at"`
	Duration     int32          `json:"duration"`
	HourlyRate   sql.NullString `json:"hourly_rate"`
	TotalAmount  sql.NullString `json:"total_amount"`
	StudentNotes sql.NullString `json:"student_notes"`
	TutorNotes   sql.NullString `json:"tutor_notes"`
	MeetingLink  sql.NullString `json:"meeting_link"`
	Rating       sql.NullInt32  `json:"rating"`
	Review       sql.NullString `json:"review"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	UpdatedAt    sql.NullTime   `json:"updated_at"`
}

type User struct {
	ID                    uuid.UUID             `json:"id"`
	SpaceID               uuid.UUID             `json:"space_id"`
	Username              string                `json:"username"`
	Email                 string                `json:"email"`
	Password              string                `json:"password"`
	FullName              string                `json:"full_name"`
	Avatar                sql.NullString        `json:"avatar"`
	Bio                   sql.NullString        `json:"bio"`
	Verified              sql.NullBool          `json:"verified"`
	Roles                 []string              `json:"roles"`
	Level                 sql.NullString        `json:"level"`
	Department            sql.NullString        `json:"department"`
	Major                 sql.NullString        `json:"major"`
	Year                  sql.NullInt32         `json:"year"`
	Interests             []string              `json:"interests"`
	FollowersCount        sql.NullInt32         `json:"followers_count"`
	FollowingCount        sql.NullInt32         `json:"following_count"`
	MentorStatus          sql.NullString        `json:"mentor_status"`
	TutorStatus           sql.NullString        `json:"tutor_status"`
	Status                sql.NullString        `json:"status"`
	Settings              pqtype.NullRawMessage `json:"settings"`
	PhoneNumber           string                `json:"phone_number"`
	AdditionalPhoneNumber sql.NullString        `json:"additional_phone_number"`
	CreatedAt             sql.NullTime          `json:"created_at"`
	UpdatedAt             sql.NullTime          `json:"updated_at"`
	// Whether the account is currently locked due to security reasons
	IsLocked bool `json:"is_locked"`
	// Timestamp until which the account is locked (NULL if not locked or permanently locked)
	LockedUntil sql.NullTime `json:"locked_until"`
	// Counter for consecutive failed login attempts
	FailedLoginAttempts int32 `json:"failed_login_attempts"`
	// Timestamp of the last failed login attempt
	LastFailedLogin sql.NullTime `json:"last_failed_login"`
	SuspendedUntil  sql.NullTime `json:"suspended_until"`
}

type UserSession struct {
	ID           uuid.UUID      `json:"id"`
	UserID       uuid.UUID      `json:"user_id"`
	SpaceID      uuid.UUID      `json:"space_id"`
	Username     string         `json:"username"`
	RefreshToken string         `json:"refresh_token"`
	UserAgent    string         `json:"user_agent"`
	IpAddress    sql.NullString `json:"ip_address"`
	IsBlocked    bool           `json:"is_blocked"`
	LastActivity sql.NullTime   `json:"last_activity"`
	ExpiresAt    time.Time      `json:"expires_at"`
	CreatedAt    sql.NullTime   `json:"created_at"`
}

// Tracks user account suspensions and bans
type UserSuspension struct {
	ID             uuid.UUID      `json:"id"`
	UserID         uuid.UUID      `json:"user_id"`
	SuspendedBy    uuid.UUID      `json:"suspended_by"`
	Reason         string         `json:"reason"`
	Notes          sql.NullString `json:"notes"`
	SuspendedAt    time.Time      `json:"suspended_at"`
	SuspendedUntil sql.NullTime   `json:"suspended_until"`
	IsPermanent    bool           `json:"is_permanent"`
	CreatedAt      time.Time      `json:"created_at"`
}
