// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createSession = `-- name: CreateSession :one
INSERT INTO user_sessions (
    id,
    user_id,
    username,
    refresh_token,
    user_agent,
    is_blocked,
    space_id,
    ip_address,
    last_activity,
    expires_at
    )
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, user_id, space_id, username, refresh_token, user_agent, ip_address, is_blocked, last_activity, expires_at, created_at
`

type CreateSessionParams struct {
	ID           uuid.UUID      `json:"id"`
	UserID       uuid.UUID      `json:"user_id"`
	Username     string         `json:"username"`
	RefreshToken string         `json:"refresh_token"`
	UserAgent    string         `json:"user_agent"`
	IsBlocked    bool           `json:"is_blocked"`
	SpaceID      uuid.UUID      `json:"space_id"`
	IpAddress    sql.NullString `json:"ip_address"`
	LastActivity sql.NullTime   `json:"last_activity"`
	ExpiresAt    time.Time      `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (UserSession, error) {
	row := q.db.QueryRowContext(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.Username,
		arg.RefreshToken,
		arg.UserAgent,
		arg.IsBlocked,
		arg.SpaceID,
		arg.IpAddress,
		arg.LastActivity,
		arg.ExpiresAt,
	)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SpaceID,
		&i.Username,
		&i.RefreshToken,
		&i.UserAgent,
		&i.IpAddress,
		&i.IsBlocked,
		&i.LastActivity,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT id, user_id, space_id, username, refresh_token, user_agent, ip_address, is_blocked, last_activity, expires_at, created_at
FROM user_sessions
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetSession(ctx context.Context, id uuid.UUID) (UserSession, error) {
	row := q.db.QueryRowContext(ctx, getSession, id)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SpaceID,
		&i.Username,
		&i.RefreshToken,
		&i.UserAgent,
		&i.IpAddress,
		&i.IsBlocked,
		&i.LastActivity,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
